language: java
dist: precise
jdk:
  - oraclejdk8
  - openjdk7 
notifications:
  email: false
script:
  - mvn clean install
after_script:
  - mvn test
before_install:
  - pip install --user codecov
after_success:
  - codecov
